### ISSUE TITLE
Access to repository

### ISSUE THREAD

**Issue by ptgolden** [editorsnotes/react-jsonld-editor#2]
Could you either add me as a collaborator or move this (and rybesh/edit-with-lov) to the Editors' Notes organization?

**Comment by rybesh** [comment]
https://github.com/editorsnotes/react-jsonld-editor
https://github.com/editorsnotes/edit-with-lov
https://github.com/editorsnotes/immutable-jsonld

**Comment by ptgolden** [comment]
Can you also add me as a collaborator to those projects on NPM? :pray:

**Comment by rybesh** [comment]
yep: https://www.npmjs.com/~ptgolden
